### PR TITLE
Use page header 8ff as time fill

### PR DESCRIPTION
**Pull request by pengi**
Great software, Thanks.

Looking at the specification, page 13, it says:

> Time filling headers: Page header packets with the page number FF which are inserted into the
transmission for the sole reason of maintaining a real-time clock display.

Using page number 8ff for that fill line means page 200, as previous fill line was using, won't be occupied, but just a non-visible page. It also has flags set so that page should be ignored, and won't interfere.

Have only tested on my samsung tv ue50es6715

### CODE REVIEW

**Comment by peterkvt80** [comment]
All MRG inserters used a page/row packet 8/25 as filler, not a header. If you send a header then you won't be able to send a new header until the next field and this will delay magazine 8. In the era of subtitles any delay needed to be minimised.

**Comment by pengi** [comment]
I've updated the PR. is that better?

It's magazine 8, packet 25, and rest is spaces (0x20)

**Comment by peterkvt80** [comment]
I'm not really worried about what you use as filler, there are pros and cons both ways. I was just mentioning the historical practise. Where the MRG strategy goes wrong is if you have an empty or low priority magazine then the header clock won't update regularly. On subtitles you get away with it because the header line is suppressed.

**Comment by ali1234** [comment]
I can't even remember what my filler packet is any more, so I'll merge this one purely because you wrote a comment. Thanks :)

**Pull request merged**
